# Copyright (C) 2016 DeathCore <http://www.noffearrdeathproject.org/>
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

language: cpp

git:
  depth: 1

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install libace-dev
  - sudo apt-get install libncurses5-dev
  - sudo apt-get install build-essential autoconf libtool make cmake git-core patch wget links zip unzip unrar
  - sudo apt-get install openssl libssl-dev mysql-server mysql-client libmysqlclient15-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  
install:
  - mysql -uroot -e 'create database test_mysql;'
  - mkdir bin
  - cd bin
  - cmake ../ -DSCRIPTS=1 -DTOOLS=1 -DSCRIPTS="dynamic" -DSERVERS=1 -DNOJEM=1 -DWITH_DYNAMIC_LINKING=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=check_install
  - cd ..

script:
  - $CXX --version
  - mysql -u root -h 127.0.0.1 < sql/create/create_mysql.sql
  - mysql -udeathcore -pdeathcore auth -h 127.0.0.1 < sql/base/auth_database.sql
  - cat sql/updates/auth/4.3.4/*_auth.sql -h 127.0.0.1 | mysql -udeathcore -pdeathcore auth
  - mysql -udeathcore -pdeathcore characters -h 127.0.0.1 < sql/base/characters_database.sql
  - cat sql/updates/characters/4.3.4/*_characters.sql | mysql -udeathcore -pdeathcore characters
  - mysql -udeathcore -pdeathcore world -h 127.0.0.1 < sql/base/dev/world_database.sql
  - cat sql/updates/world/4.3.4/*_world.sql -h 127.0.0.1 | mysql -udeathcore -pdeathcore world
  - mysql -uroot < sql/create/drop_mysql.sql
  - cd bin
  - make -j 8 -k && make install
  - cd check_install/bin
